name: dynamicpass
description: "Dynamic password rotating application"
publish_to: 'none'
version: 0.1.2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.3.0
  local_auth_android: ^1.0.6
  qr_flutter: ^4.1.0
  crypto: ^3.0.3
  provider: ^6.0.5
  flutter_animate: ^4.5.0
  mobile_scanner: ^7.1.3
  lottie: ^3.3.2
  vibration: ^3.1.4
  flutter_launcher_icons: ^0.13.1
  http: ^1.1.0
  uuid: ^4.2.0
  shared_preferences: ^2.3.2
  characters: ^1.3.0
  flutter_secure_storage: ^9.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  adaptive_icon_background: "#081225" # Optional (Android 8.0+ adaptive icons)
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/fusion.json
    - assets/animations/fingerprint_scan.json
    - assets/animations/unlock_success.json
    - assets/images/background.png


  
